apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app.kubernetes.io/name: {{ include "helloworld-chart.name" . }}
    helm.sh/chart: {{ include "helloworld-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.167.196
  clusterIPs:
  - 10.100.167.196
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 30002
  selector:
    run: hello-world-example
    app.kubernetes.io/name: {{ include "helloworld-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
  status:
    loadBalancer: {}